### ISSUE TITLE
[feature] frontend UI 코드 전체적으로 작성하기

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/cashbook-19#16]
## 🖥 필수 요구사항

1. - [x] 헤더영역 작성
      - [x] view 코드
      - [x] template html
      - [x] module.scss
2. - [x] 사용기록 리스트
      - [x] view 코드
      - [x] template html
      - [x] module.scss
3. - [ ] 달력
      - [ ] view 코드
      - [ ] template html
      - [ ] module.scss
4. - [ ] 그래프
      - [ ] view 코드
      - [ ] template html
      - [ ] module.scss

## ⏰ 예상 완료 시간

8시간

**Comment by Kyun2da** [comment]
이걸 왜 닫았지.. 다시 열게용
