### ISSUE TITLE
[feature] Header view 디테일 추가

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/cashbook-19#35]
## 🖥 필수 요구사항

1. - [x] router 이동에 따라서 현재 화면에 해당하는 아이콘 활성화 표시
2. - [x] 달 옆에 화살표 누르면 달 상태 변경시키기

## ⏰ 예상 완료 시간

2시간

**Comment by Kyun2da** [comment]
interface DateState {
  year: number;
  month: number;
}

interface StoreState {
  router: RouterState;
  login: LoginState | null;
  categories: Category[];
  payments: Payment[];
  records: CashRecord[];
  date: DateState;
}
