### ISSUE TITLE
[refactoring] Component class를 만들어서 공통 기능 묶기

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/cashbook-19#43]
현재 UI는 Observer class를 상속받아서 구현하고 있습니다.

```typescript
interface Observer {
  // Gets called by the Subject::notify method.
  update(data: StoreState): void;
}
```

main view만 살펴 봤을때 아래와 같은 구조를 가지고 있습니다.

```typescript
class Main implements Observer {
  template(state: StoreState): string { }
  render(state: StoreState): void { }
  update(state: StoreState): void { }
  addEventHandler(state: StoreState, parent: HTMLElement): void { }
}
```

다른 UI 관련 class들도 위와 동일한 구조를 가지고 있습니다.
사실 구조가 너무 작아서 굳이 묶지 않았던 거지만 의미를 좀더 구체적으로 하기 위해서 공동 기능들을 담은 class를 하나 만들면 좋겠습니다.

```typescript
class UiComponent implements Observer {
  private store: State;
  private router: Router;

  constructor(store: State, router: Router) {
    this.store = store;
    this.router = router;
  }

  shouldUpdate(state: StoreState): boolean { }

  update(state: StoreState): void {
    if (this.shouldUpdate(state)) {
      this.render(state);
    }
  }

  render(state: StoreState): void { }
  addEventHandler(state: StoreState, parent: HTMLElement): void { }
  template(state: StoreState): string { }
}
```

우선 위 코드가 완벽하지는 않지만 제안만 합니다.
_'이게 과연 장기적으로 옳은 코드인가?'_ 와 같은 고민으로 진행을 못하는 것보다 현재 우리가 필요한 코드를 작성해 나가는게 더 중요하다고 생각합니다.
아 물론 이런 말은 하는건 제가 그렇기 때문입니다 ㅋㅋ

**Comment by Kyun2da** [comment]
좋은 의견입니다. 점점 파일 구조가 커지면서 리펙토링의 필요성을 느끼고 있습니다. 렌더링도 shouldUdate로 제어를 해줘야만 상관없는 데이터가 변경되었을 때 리렌더를 방지할 수 있을 것 같습니다.

**Comment by Kyun2da** [comment]
이 방식이 그럼 UI클래스를 선언해서 아래와 같이 쓰자는 말씀이신가요?
```js
class Main implements UIComponent {
  template(state: StoreState): string { }
  render(state: StoreState): void { }
  shouldUpdate(state: StoreState): boolean { }
  update(state: StoreState): void { }
  addEventHandler(state: StoreState, parent: HTMLElement): void { }
}
```

아 추가로 shouldUpdate에서 어떻게 이전의 store를 가져와서 변경된 상태와 비교할 수 있을까요?

**Comment by TsooranKim** [comment]
> 아 추가로 shouldUpdate에서 어떻게 이전의 store를 가져와서 변경된 상태와 비교할 수 있을까요?

@Kyun2da 앗! 그러게요. 그걸 생각안했네요 ㅎㅎ
흠... Subject의 상태는 어차피 immutable 하니 update에 state만 넘겨주는게 아니라
`update(prevState: StoreState, nextState: StoreState)`로 이전, 다음 상태를 같이 넘겨주는게 어떨까요?
