### ISSUE TITLE
[document] 앞으로 남은 이슈 정리

### ISSUE THREAD

**Issue by Kyun2da** [woowa-techcamp-2021/cashbook-19#50]
### 프론트

1. - [x] 헤더 로그인 api와 연동하여 로그인 및 로그아웃 구현
2. - [x] 에러 모달 만들기
3. - [x] 메인 페이지 폼 레코드 추가 구현
4. - [ ] 그래프 페이지 꺾은선 그래프
5. - [x] 배포

### 백엔드

1. - [x] 카테고리 추가, 삭제 api (폼 관련)
2. - [x] 결제 수단 추가, 삭제 api (폼 관련)
3. - [x] 레코드 추가 api (폼 관련)
4. - [ ] 카테고리 1년 합계 api (꺾은선 그래프 관련)
5. - [x] 자동 배포

## 📝 선택 요구사항

1. - [x] 캘린더 일자 누르면 해당 일에 관련된 레코드 아래에 렌더링
2. - [x] 레코드 호버시 수정 삭제 버튼 떠서 수정 삭제 기능
3. - [x] 레코드 수정 삭제 api
4. - [x] 반응형 페이지
5. - [ ] 기타 생각나는 애니메이션

## ⏰ 예상 완료 시간

2days

**Comment by Kyun2da** [comment]
남은 2일동안 두고 보면 좋을 것 같아서
생각나는 이슈들 정리해봤습니다~

더 있으면 수정으로 추가해주시면 될 것 같습니다!

**Comment by TsooranKim** [comment]
화이팅~
