### ISSUE TITLE
[bug] 버그 제보 받습니다.

### ISSUE THREAD

**Issue by Kyun2da** [woowa-techcamp-2021/cashbook-19#85]
## 🧯 버그 설명

버그를 샅샅이 찾아내 없애보자~

## ⚙️ 버그 발생 상황

- [x] 로그인 누르고 깃허브 authorization cancel누르면 에러나는 문제 [auth]
- [x] 캘린더 페이지 렌더링 안되는 문제 [main]
- [x] 로그인 안하고 등록 버튼 누르는 것 에러처리 안되있음 [main]
- [x] 레코드 한글 세로정렬 안되있음 [main]
- [x] 메인리스트 필터쪽 바깥부분 누르면 에러로그뜸 [main]
- [x] 카테고리, 페이먼트 모달 바깥 부분 누르면 active 비활성화 되야할듯 [main]

## 추가내용

**Comment by TsooranKim** [comment]
bugfix/#85-xxxx 이런식으로 따면 좋겠습니다.
